name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: List Files After Checkout
        run: |
          pwd
          ls -la
      - name: Simple JavaScript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Luis
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"